{{- if .Values.ingress.enabled }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "fullname" . }}
  annotations:
    {{- if .Values.ingress.tls.enabled }}
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.tls.clusterIssuer }}
    {{- end }}
    ingress.kubernetes.io/force-ssl-redirect: "true"      
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
  - secretName: {{ .Values.ingress.tls.secret }}
    hosts:
    - {{ .Values.ingress.host }}
  {{- end }}    
  rules:
  - host: {{.Values.ingress.host}}
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ template "fullname" . }}
          servicePort: {{ .Values.service.externalPort }}
{{- end }}
